version: '3.3'
services:
  langchain_retrieval:
    container_name: langchain_retrieval
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    build: retrieval
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: "host"
    environment:
      - TZ=Europe/Moscow
      - OPENAI_API_KEY=your_key